### ISSUE TITLE
Break points not working in env: vscode, sjasmplus, Cspect

### ISSUE THREAD

**Issue by githubtester2** [maziac/z80-sample-program#1]
Hello,

Break points not working in the following environment:

sjasmplus 1.18.2
Cspect 2.12.36
vscode 1.56.0
DeZogPlugin.dll 2.0.1

The project is attached as zip archive.

Best Regards!
[z80-sample-program-master.zip](https://github.com/maziac/z80-sample-program/files/6452518/z80-sample-program-master.zip)

**Comment by maziac** [comment]
I just tested with the current version, set a breakpoint at e.g. line 65 in main.asm and it was working.
Most probably the older Cspect version is the problem. Please try 2.13.01 (DeZog 2.2.4, DeZogPlugin 2.0.1).

I updated the version numbers in the z80-sample-program.

**Comment by githubtester2** [comment]
Thank you so much for such a quick response!

I tried to download Cspect 2.13.01 but Chrome blocked it - it says it's a dangerous file.

Do you have any advice on what to do next? Did Chrome or an antivirus program give you similar warnings?

I tried to download from this location: http://cspect.org/ <http://cspect.org/>

Best Regards!

**Comment by maziac** [comment]
Every new version of cspect gets blocked.
That's normal.

**Comment by githubtester2** [comment]
Thank you a lot for your response!

Best Regards!

**Comment by maziac** [comment]
Does the problem still exist or can I close the issue?

**Comment by maziac** [comment]
Closed as I got no further response.
